version: '3.1'

services:
  shift_planner:
    command: npm run start:dev
    # command: npm run start:prod:docker
    working_dir: /home/node/shift-planner
    restart: unless-stopped
    build:
      target: development
      args:
        ENVIRONMENT: development
        DB_HOST: db
      # target: production
      # args:
      #   ENVIRONMENT: production
      #   DB_HOST: db
    volumes:
      - ./src:/home/node/shift-planner/src
    ports:
      - '9230:9229'
      - '3000:3000'
    depends_on:
      - db

  # Use root/example as user/password credentials
  db:
    image: mysql # https://hub.docker.com/_/mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: shift_planner
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:

networks:
  default: